monitoring:
  enabled: true
  interval: 30s
  dashboards: true
  alarms: false

client:
  extraConfig: |
    {
        "telemetry":
            {
                "prometheus_retention_time": "24h",
                "disable_hostname": true
            }
    }
